### ISSUE TITLE
RedPen plugin does not work with IntelliJ IDEA CE 2018

### ISSUE THREAD

**Issue by johnblommers** [redpen-cc/redpen-intellij-plugin#17]
We had a working RedPen with IntelliJ IDEA CE 2017.3.4. Then we used the update process within IDEA to bring it to the 2018.1.1 version. Now the red wiggly lines of RedPen never appear. The only workaround we found is to delete the 2018 version of IDEA and reinstall the 2017 version.

This is on macOS X 10.11.6 El Capitan. We're using the RedPen IntelliJ Plugin 1.8.1.

**Comment by takahi-i** [comment]
Thank you very much for the valuable report @johnblommers!  I will look into the problem.

**Comment by hameerabbasi** [comment]
It'd be nice to have a fix for this, as IntelliJ 2018.x have been out for a while now.

**Comment by takahi-i** [comment]
Hi @hameerabbasi, Thank you for the remind. I tried RedPen plugin in  IntelliJ 2018.1 and confirmed the plugin works.

The following is the image of the IntelliJ.

<img width="1043" alt="screen shot 2018-06-25 at 17 50 47" src="https://user-images.githubusercontent.com/339436/41854401-19fb5364-78cb-11e8-8e79-8bd3bf2b9b16.png">

**Comment by hameerabbasi** [comment]
This problem might be PyCharm specific then. I'm going to Settings > Preferences and clicking browse repositories. Then, searching for RedPen and clicking Install.

After it downloads, it doesn't ask for an IDE restart or tell me that the plugin is installed. I can't find it in my plugin list either.

**Comment by takahi-i** [comment]
I see. I will try RedPen with PyCharm.

**Comment by takahi-i** [comment]
Reproduced error in PyCharm.

Got the following error messages in ~/Library/Logs/PyCharmCE2018.1/idea.log.

```
2018-06-26 17:07:07,817 [ 430826]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 2018/06/26 16:47)
2018-06-26 17:07:11,495 [ 434504]   WARN - Settings.impl.PluginDownloader - Invalid filename returned by a server
java.io.IOException: Invalid filename returned by a server
        at com.intellij.openapi.updateSettings.impl.PluginDownloader.guessFileName(PluginDownloader.java:270)
        at com.intellij.openapi.updateSettings.impl.PluginDownloader.access$000(PluginDownloader.java:36)
        at com.intellij.openapi.updateSettings.impl.PluginDownloader$1.process(PluginDownloader.java:232)
        at com.intellij.openapi.updateSettings.impl.PluginDownloader$1.process(PluginDownloader.java:227)
        at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:403)
        at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:335)
        at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:403)
        at com.intellij.util.io.HttpRequests.process(HttpRequests.java:383)
        at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:49)
        at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:252)
        at com.intellij.openapi.updateSettings.impl.PluginDownloader.downloadPlugin(PluginDownloader.java:227)
        at com.intellij.openapi.updateSettings.impl.PluginDownloader.prepareToInstall(PluginDownloader.java:128)
        at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:227)
        at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:115)
        at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:54)
        at com.intellij.ide.plugins.PluginManagerMain$5.run(PluginManagerMain.java:435)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
        at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by hameerabbasi** [comment]
I can't tell from this on reading the traceback... Is this a PyCharm issue, a RedPen issue, or a plugin distribution issue? Maybe your filename is compatible with IntelliJ but not with PyCharm for some reason? Maybe the server is messing with filenames for different IDEs? Just throwing ideas out here.

**Comment by takahi-i** [comment]
Confirmed we can install RedPen plugin downloading from plugin home page.

https://plugins.jetbrains.com/plugin/8210-redpen-plugin

Download the zipped plugin file from the above URL and expand it in the plugin directory described in the following page.

https://stackoverflow.com/questions/1226066/how-do-i-install-a-specific-version-of-an-idea-plugin

I still do not know why we cannnot install the plugin from the IntelliJ UI...

**Comment by takahi-i** [comment]
Finally I succeeded to install RedPen in Pycharm through UI. @hameerabbasi Can you please try it again?

**Comment by hameerabbasi** [comment]
I’ll check tomorrow, hopefully.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hameerabbasi** [comment]
I just tested. The installation from UI works fine now. Haven't tested for any other bugs, though.

**Comment by takahi-i** [comment]
Thanks! I close this issue.
